;; This code was automatically generated by the 'metav' library.
(ns metav.meta)

(def module-name "metav")
(def path ".")
(def version "1.6.5")
(def tag "v1.6.5")
(def generated-at "2020-02-20T16:39:22Z")
