;; This code was automatically generated by the 'metav' library.
(ns metav.meta)

(def module-name "metav")
(def path ".")
(def version "1.6.1")
(def tag "v1.6.1")
(def generated-at "2019-10-28T21:45:36Z")
