;; This code was automatically generated by the 'metav' library.
(ns metav.meta)

(def module-name "metav")
(def path ".")
(def version "1.6.4")
(def tag "v1.6.4")
(def generated-at "2020-02-19T16:55:49Z")
